force-app/main/default/objects/Open_Hours__c/Open_Hours__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Referral Open Hours</label>
    <nameField>
        <displayFormat>Open Hours-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Open Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Hours__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Hours</relationshipLabel>
    <relationshipName>Hours</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ServiceRecommendation.cls
public class ServiceRecommendation {
  @AuraEnabled
  public Service__c Service { get; set; }

  @AuraEnabled
  public Decimal Relevance { get; set; }

  @AuraEnabled
  public String ServiceId { get; set; }

  @AuraEnabled
  public String ProviderName { get; set; }

  @AuraEnabled
  public String AccountId { get; set; }

  @AuraEnabled
  public String ProgramName { get; set; }

  @AuraEnabled
  public String ProgramType { get; set; }

  @AuraEnabled
  public String ProgramDescription { get; set; }

  @AuraEnabled
  public Open_Hours__c TodaysHours { get; set; }

  @AuraEnabled
  public String MailingStreet { get; set; }

  @AuraEnabled
  public String MailingCity { get; set; }

  @AuraEnabled
  public String Website { get; set; }

  @AuraEnabled
  public Decimal Rating { get; set; }

  @AuraEnabled
  public Decimal Distance { get; set; }

  @AuraEnabled
  public List<Comment> Comments { get; set; }

  @AuraEnabled
  public Boolean Hidden { get; set; }

  @AuraEnabled
  public Integer totalRatings { get; set; }

  @AuraEnabled
  public Integer Preferred { get; set; }

  @AuraEnabled
  public List<Indicator> Indicators { get; set; }

  // dynamic getter for supporting returning certain properties
  public Decimal getValue(string property) {
    if (property == 'Distance') {
      return this.Distance;
    }
    if (property == 'Rating') {
      return this.Rating;
    }
    if (property == 'Preferred') {
      return this.Preferred;
    }
    return null;
  }

  public class Indicator {
    @AuraEnabled
    public String IndicatorType { get; set; }

    @AuraEnabled
    public String IndicatorValue { get; set; }

    @AuraEnabled
    public Decimal IndicatorPercentile { get; set; }
  }

  public class Comment {
    @AuraEnabled
    public String CommentText { get; set; }
  }
}