force-app/main/default/objects/Open_Hours__c/Open_Hours__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Referral Open Hours</label>
    <nameField>
        <displayFormat>Open Hours-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Open Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Hours__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Open_Hours__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Hours</relationshipLabel>
    <relationshipName>Hours</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/City__c.field-meta.xml
<CustomField>
    <label>City</label>
    <type>Text</type>
    <fullName>City__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Phone__c.field-meta.xml
<CustomField>
    <label>Phone</label>
    <type>Phone</type>
    <fullName>Phone__c</fullName>
</CustomField>

force-app/main/default/objects/Service__c/fields/Street__c.field-meta.xml
<CustomField>
    <label>Street</label>
    <type>Text</type>
    <fullName>Street__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Goods</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Money</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Website__c.field-meta.xml
<CustomField>
    <label>Website</label>
    <type>Url</type>
    <fullName>Website__c</fullName>
</CustomField>

force-app/main/default/objects/Service__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <label>Zip Code</label>
    <type>Text</type>
    <fullName>Zip_Code__c</fullName>
    <length>10</length>
</CustomField>

force-app/main/default/classes/ServicePrint.cls
public with sharing class ServicePrint {


    @AuraEnabled
    public Service__c service {get;set;}

    public String ProviderName {get;set;}
    public String Sunday {
        get {
            if(Sunday == null){
                Sunday = 'S: Closed';
            }else{
                Sunday = Sunday;
            }
        return Sunday;}
        set;
    }
    public String Monday {
        get {
            if(Monday == null){
                Monday = 'M: Closed';
            }else{
                Monday = Monday;
            }
        return Monday;}
        set;
    }
    public String Tuesday {
        get {
            if(Tuesday == null){
                Tuesday = 'T: Closed';
            }else{
                Tuesday = Tuesday;
            }
        return Tuesday;}
        set;
    }
    public String Wednesday {
        get {
            if(Wednesday == null){
                Wednesday = 'W: Closed';
            }else{
                Wednesday = Wednesday;
            }
        return Wednesday;}
        set;
    }
    public String Thursday {
        get {
            if(Thursday == null){
                Thursday = 'T: Closed';
            }else{
                Thursday = Thursday;
            }
        return Thursday;}
        set;
    }
    public String Friday {
        get {
            if(Friday == null){
                Friday = 'F: Closed';
            }else{
                Friday = Friday;
            }
        return Friday;}
        set;
    }
    public String Saturday {
        get {
            if(Saturday == null){
                Saturday = 'S: Closed';
            }else{
                Saturday = Saturday;
            }
        return Saturday;}
        set;
    }

    public ServicePrint() {
        String servId = [SELECT Id FROM Service__c WHERE id =:ApexPages.currentPage().getParameters().get('servId')].Id;
        System.debug('serviceId' + servId);
        List<Open_Hours__c> allHours = getOpenHours(servId);
    }

    public Service__c getServices(string serviceId) {
        Service__c newserv = [SELECT Id, Name, Account__r.Name, Type__c,Description__c, Website__c, Street__c, City__c, Zip_Code__c, Phone__c FROM Service__c WHERE Id = :serviceId];
        ProviderName = newserv.Account__r.Name;
        return newserv;
    }

    public List<Open_Hours__c> getOpenHours(string serviceId){
        system.debug('serviceId' + serviceId);
        List<Open_Hours__c> hrs = [SELECT Id,Day__c, End_Time__c, Start_Time__c, Service__c FROM Open_Hours__c WHERE Service__c = :serviceId];
        
        for(Open_Hours__c hour: hrs){
            switch on hour.Day__c {
                when 'Sunday' {
                    Sunday = 'S: ' + Datetime.newInstance(Date.Today(), hour.Start_Time__c).format('hh:mm a') + ' - ' + Datetime.newInstance(Date.Today(), hour.End_Time__c).format('hh:mm a');
                }
                when 'Monday' {
                    Monday = 'M: ' + Datetime.newInstance(Date.Today(), hour.Start_Time__c).format('hh:mm a') + ' - ' + Datetime.newInstance(Date.Today(), hour.End_Time__c).format('hh:mm a');
                }
                when 'Tuesday' {
                    Tuesday = 'T: ' + Datetime.newInstance(Date.Today(), hour.Start_Time__c).format('hh:mm a') + ' - ' + Datetime.newInstance(Date.Today(), hour.End_Time__c).format('hh:mm a');
                }
                when 'Wednesday' {
                    Wednesday = 'W: ' + Datetime.newInstance(Date.Today(), hour.Start_Time__c).format('hh:mm a') + ' - ' + Datetime.newInstance(Date.Today(), hour.End_Time__c).format('hh:mm a');
                }
                when 'Thursday' {
                    Thursday = 'T: ' + Datetime.newInstance(Date.Today(), hour.Start_Time__c).format('hh:mm a') + ' - ' + Datetime.newInstance(Date.Today(), hour.End_Time__c).format('hh:mm a');
                    System.debug(Thursday);
                }
                when 'Friday' {
                    Friday = 'F: ' + Datetime.newInstance(Date.Today(), hour.Start_Time__c).format('hh:mm a') + ' - ' + Datetime.newInstance(Date.Today(), hour.End_Time__c).format('hh:mm a');
                }
                when 'Saturday' {
                    Saturday = 'S: ' + Datetime.newInstance(Date.Today(), hour.Start_Time__c).format('hh:mm a') + ' - ' + Datetime.newInstance(Date.Today(), hour.End_Time__c).format('hh:mm a');
                }
            }
        }
        service = getServices(serviceId);
        return hrs;
    
    }

    @AuraEnabled
    public static String PrintPage(String serviceId){
        Attachment attach = new Attachment();
        attach.body = Blob.valueOf('');  
        Blob body = Blob.valueOf(''); 

        try {
           	PageReference nr = new PageReference('/apex/refrec__ServicePrintPage?servId=' + serviceId);
            //nr.getParameters().put('service', service);
            body = nr.getContentAsPDF();
            

            // need to pass unit test -- current bug
        } catch (Exception err) {
            System.debug('An Error occurred generating the PDF: ' + err);
            body = Blob.valueOf('Err');
        }
        attach.Body = body;
        
        // Create name with today's date
        Integer count = 1;
        attach.Name = 'Referral - ' + Datetime.now().format('yyyy-MM-dd') + ' - ' + String.valueOf(count) + '.pdf';
        attach.IsPrivate = false; //make public
        attach.ParentId = serviceId; //attach pdf to record
        insert attach;

        String fullURL = URL.getSalesforceBaseUrl().toExternalForm() + '/apex/refrec__ServicePrintPage?servId=' + serviceId;
        System.debug(fullURL);
        return fullURL;

    }
}