force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Service Referral</label>
    <pluralLabel>Service Referrals</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>Ref-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Score__c.field-meta.xml
<CustomField>
    <label>Score</label>
    <type>Number</type>
    <fullName>Score__c</fullName>
    <scale>0</scale>
    <precision>1</precision>
    <description>1-5 score (star rating)</description>
    <inlineHelpText>1-5 score (star rating)</inlineHelpText>
</CustomField>

force-app/main/default/objects/Referral_Response__c/Referral_Response__c.object-meta.xml
<CustomObject>
    <description>Records capturing the questions and response messages sent to client regarding their referrals</description>
    <label>Referral Response</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Referral Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question that was asked of the client, sent via a message</description>
    <inlineHelpText>The question that was asked of the client, sent via a message</inlineHelpText>
    <label>Question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Response__c/fields/Referral__c.field-meta.xml
<CustomField>
    <fullName>Referral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The referral record regarding which the question messages were sent to the client</description>
    <inlineHelpText>The referral record regarding which the question messages were sent to the client</inlineHelpText>
    <label>Referral</label>
    <referenceTo>Referral__c</referenceTo>
    <relationshipLabel>Referral Responses</relationshipLabel>
    <relationshipName>Referral_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral_Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>The response received by the client</description>
    <inlineHelpText>The response received by the client</inlineHelpText>
    <label>Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReferralResponseHelper.cls
public with sharing class ReferralResponseHelper {
    
    public static void saveReferralScore(Id referralId, Integer score) {
        if (referralId != null && score != null) {
            Referral__c refer = new Referral__c (
                Id = referralId,
                Score__c = score
            );
            update refer;
        }
    }

    public static Referral_Response__c createQuestionRecord(String referralId, String question) {
        Referral_Response__c refRes = new Referral_Response__c (
            Referral__c = referralId,
            Question__c = question
        );
        insert refRes;

        return refRes;
    }

    public static Referral_Response__c updateRecordWithResponse(String referralResponseId, String response) {
        Referral_Response__c refRes = new Referral_Response__c (
            Id = referralresponseId,
            Response__c = response
        );
        update refRes;

        return refRes;
    }
}