force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Exclusion__c/Service_Exclusion__c.object-meta.xml
<CustomObject>
    <label>Referral Program Exclusion</label>
    <pluralLabel>Referral Program Exclusions</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>X-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Exclusion__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Exclusion__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_ServiceHide.cls
@isTest
private with sharing class Test_ServiceHide {
  static testMethod void hideForContact() {
    id contactId = getTestContactId();
    id serviceId = getTestServiceId();

    test.startTest();
    serviceHide.hide(serviceId, contactId);
    test.stopTest();

    list<Service_Exclusion__c> exclusions = getExclusions(serviceId, contactId);
    system.assertEquals(1, exclusions.size());
    system.assertEquals(contactId, exclusions[0].Contact__c);
    system.assertEquals(serviceId, exclusions[0].Service__c);
  }

  static testMethod void unhideForContact() {
    id contactId = getTestContactId();
    id serviceId = getTestServiceId();

    test.startTest();
    serviceHide.hide(serviceId, contactId);
    serviceHide.unHide(serviceId, contactId);
    test.stopTest();

    list<Service_Exclusion__c> exclusions = getExclusions(serviceId, contactId);
    system.assertEquals(0, exclusions.size());
  }

  static testMethod void hideForAll() {
    id serviceId = getTestServiceId();

    test.startTest();
    serviceHide.hide(serviceId, null);
    test.stopTest();

    list<Service_Exclusion__c> exclusions = getExclusions(serviceId, null);
    system.assertEquals(1, exclusions.size());
    system.assertEquals(null, exclusions[0].Contact__c);

    system.assertEquals(serviceId, exclusions[0].Service__c);
  }

  static testMethod void unhideForAll() {
    id serviceId = getTestServiceId();

    test.startTest();
    serviceHide.hide(serviceId, null);
    serviceHide.unHide(serviceId, null);
    test.stopTest();

    list<Service_Exclusion__c> exclusions = getExclusions(serviceId, null);
    system.assertEquals(0, exclusions.size());
  }

  private static list<Service_Exclusion__c> getExclusions(
    Id serviceId,
    Id contactId
  ) {
    return [SELECT id, Service__c, Contact__c FROM Service_Exclusion__c];
  }

  private static Id getTestContactId() {
    return [SELECT id FROM Contact WHERE LastName = 'TestContact'].Id;
  }

  private static Id getTestServiceId() {
    return [SELECT id FROM Service__c WHERE Name = 'Test Service for Hiding']
    .Id;
  }
  @testSetup
  static void makeData() {
    contact c = new Contact();
    c.LastName = 'TestContact';
    insert c;

    Service__c s = new Service__c();
    s.Name = 'Test Service for Hiding';
    insert s;
  }
}