force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Exclusion__c/Service_Exclusion__c.object-meta.xml
<CustomObject>
    <label>Referral Program Exclusion</label>
    <pluralLabel>Referral Program Exclusions</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>X-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Exclusion__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Exclusion__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/serviceHide.cls
public with sharing class serviceHide {
  @AuraEnabled
  public static void hide(id serviceId, Id contactId) {
    Service_Exclusion__c SE = new Service_Exclusion__c();
    SE.Service__c = serviceId;
    if (serviceId != null) {
      SE.Contact__c = contactId;
    }
    insert SE;
  }

  @AuraEnabled
  public static void unHide(id serviceId, Id contactId) {
    if (contactId != null) {
      delete [
        SELECT id
        FROM Service_Exclusion__c
        WHERE
          createdById = :UserInfo.getUserId()
          AND Service__c = :serviceId
          AND Contact__c = :contactId
      ];
    } else {
      delete [
        SELECT id
        FROM Service_Exclusion__c
        WHERE
          createdById = :UserInfo.getUserId()
          AND Service__c = :serviceId
          AND Contact__c = null
      ];
    }
  }
}