force-app/main/default/objects/Client_Profile__c/Client_Profile__c.object-meta.xml
<CustomObject>
    <label>Referral Client Profile</label>
    <pluralLabel>Referral Client Profiles</pluralLabel>
    <description>added from sfdx plugin</description>
    <label>Client Profile</label>
    <pluralLabel>Client Profiles</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>CP-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Profile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Profile</relationshipLabel>
    <relationshipName>Client_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Profile__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <label>Date of Birth</label>
    <type>Date</type>
    <fullName>Date_of_Birth__c</fullName>
</CustomField>

force-app/main/default/objects/Open_Hours__c/Open_Hours__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Referral Open Hours</label>
    <nameField>
        <displayFormat>Open Hours-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Open Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Hours__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Open_Hours__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Hours</relationshipLabel>
    <relationshipName>Hours</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Service Referral</label>
    <pluralLabel>Service Referrals</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>Ref-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Score__c.field-meta.xml
<CustomField>
    <label>Score</label>
    <type>Number</type>
    <fullName>Score__c</fullName>
    <scale>0</scale>
    <precision>1</precision>
    <description>1-5 score (star rating)</description>
    <inlineHelpText>1-5 score (star rating)</inlineHelpText>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RefRecSettings__mdt/RefRecSettings__mdt.object-meta.xml
<CustomObject>
    <label>Referral Recommendations Setting</label>
    <pluralLabel>Referral Recommendations Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/RefRecSettings__mdt/fields/Default_Latitude__c.field-meta.xml
<CustomField>
    <fullName>Default_Latitude__c</fullName>
    <defaultValue>37.7897</defaultValue>
    <description>Used to find services when no information about the Client&apos;s location is provided.  North is positive latitude, south is negative.</description>
    <inlineHelpText>Used to find services when no information about the Client&apos;s location is provided.  North is positive latitude, south is negative.</inlineHelpText>
    <label>Default Latitude</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RefRecSettings__mdt/fields/Default_Longitude__c.field-meta.xml
<CustomField>
    <fullName>Default_Longitude__c</fullName>
    <defaultValue>-122.3972</defaultValue>
    <description>Used to find services when no information about the Client&apos;s location is provided.  East is positive longitude, west is negative.</description>
    <inlineHelpText>Used to find services when no information about the Client&apos;s location is provided.  East is positive longitude, west is negative.</inlineHelpText>
    <label>Default Longitude</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RefRecSettings__mdt/fields/Default_Max_Distance__c.field-meta.xml
<CustomField>
    <fullName>Default_Max_Distance__c</fullName>
    <defaultValue>25</defaultValue>
    <description>In miles, how far from the client or default location should a search extend</description>
    <inlineHelpText>In miles, how far from the client or default location should a search extend</inlineHelpText>
    <label>Default Max Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/City__c.field-meta.xml
<CustomField>
    <label>City</label>
    <type>Text</type>
    <fullName>City__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>4</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Maximum_Age__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Age__c</fullName>
    <label>Maximum Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Minimum_Age__c.field-meta.xml
<CustomField>
    <label>Minimum Age</label>
    <type>Number</type>
    <fullName>Minimum_Age__c</fullName>
    <scale>0</scale>
    <precision>18</precision>
</CustomField>

force-app/main/default/objects/Service__c/fields/Phone__c.field-meta.xml
<CustomField>
    <label>Phone</label>
    <type>Phone</type>
    <fullName>Phone__c</fullName>
</CustomField>

force-app/main/default/objects/Service__c/fields/Preferred__c.field-meta.xml
<CustomField>
    <fullName>Preferred__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Preferred</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Street__c.field-meta.xml
<CustomField>
    <label>Street</label>
    <type>Text</type>
    <fullName>Street__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Goods</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Money</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Website__c.field-meta.xml
<CustomField>
    <label>Website</label>
    <type>Url</type>
    <fullName>Website__c</fullName>
</CustomField>

force-app/main/default/objects/Service__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <label>Zip Code</label>
    <type>Text</type>
    <fullName>Zip_Code__c</fullName>
    <length>10</length>
</CustomField>

force-app/main/default/objects/Service_Exclusion__c/Service_Exclusion__c.object-meta.xml
<CustomObject>
    <label>Referral Program Exclusion</label>
    <pluralLabel>Referral Program Exclusions</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>X-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Exclusion__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Exclusion__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Exclusions</relationshipLabel>
    <relationshipName>Exclusions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

.history/force-app/main/default/classes/getRecommendations_20200612140257.cls
public with sharing class getRecommendations {
  @AuraEnabled
  public static list<ServiceRecommendation> getRecommendations(id contactId) {
    Client_Profile__c CP = getProfile(contactId);
    List<Service__c> services = primaryQuery(CP);

    // convert to ServiceRecommendation
    list<ServiceRecommendation> output = servicesToRecommendations(services);

    // do the hours for each service
    output = addHours(output);
    // figure out which services to hide
    output = addHides(output, contactId);
    // do the comments for each service
    output = getComments(output);
    // do the Star Rating for each service
    output = addStars(output);
    // final Relevancy score + factors
    output = finalScores(output);

    return output;
  }

  // list of services with any hard filters
  // hard filters are currently Age
  public static list<Service__c> primaryQuery(Client_Profile__c client) {
    decimal age = calculateAge(client.Date_Of_Birth__c);
    decimal defaultMaxDistance = [
      SELECT Default_Max_Distance__c
      FROM RefRecSettings__mdt
    ]
    .Default_Max_Distance__c;
    return [
      SELECT
        id,
        Name,
        Account__c,
        Account__r.Name,
        Description__c,
        City__c,
        Phone__c,
        Street__c,
        Type__c,
        Website__c,
        Zip_Code__c,
        Preferred__c
      FROM Service__c
      WHERE
        (Minimum_Age__c = null
        OR Minimum_Age__c < :age)
        AND (Maximum_Age__c = null
        OR Maximum_Age__c > :age)
        AND DISTANCE(
          Location__c,
          GEOLOCATION(:client.Location__Latitude__s,
            :client.Location__Longitude__s
          ),
          'mi'
        ) < :defaultMaxDistance
    ];
  }

  public static List<ServiceRecommendation> servicesToRecommendations(
    List<Service__c> services
  ) {
    List<ServiceRecommendation> output = new List<ServiceRecommendation>();
    for (Service__c service : services) {
      ServiceRecommendation SR = new ServiceRecommendation();
      SR.Relevance = 0;
      SR.ServiceId = service.Id;
      SR.ProviderName = service.Account__r.Name;
      SR.AccountId = service.Account__c;
      SR.ProgramName = service.Name;
      SR.ProgramType = service.Type__c;
      SR.ProgramDescription = service.Description__c;
      SR.TodaysHours = null;
      SR.MailingStreet = service.Street__c;
      SR.MailingCity = service.City__c;
      SR.Website = service.Website__c;
      SR.Hidden = false;
      SR.Indicators = new List<ServiceRecommendation.Indicator>();
      SR.Comments = new List<ServiceRecommendation.Comment>();

      if (service.Preferred__c) {
        ServiceRecommendation.Indicator indicator = new ServiceRecommendation.Indicator();
        indicator.IndicatorType = 'Preferred Service';
        indicator.IndicatorValue = 'TRUE';
        SR.Indicators.add(indicator);
      }
      output.add(SR);
    }
    return output;
  }

  // would rather spend one more query to use aggregates than an unknown number of query rows
  public static List<ServiceRecommendation> addStars(
    List<ServiceRecommendation> recs
  ) {
    map<id, decimal> ratingsByService = new Map<id, decimal>();
    for (AggregateResult result : [
      SELECT Service__c, AVG(Score__c) averageScore
      FROM Referral__c
      WHERE Service__c IN :IDsFromRecommendations(recs) AND Score__c != null
      GROUP BY Service__c
    ]) {
      ratingsByService.put(
        (id) result.get('Service__c'),
        (decimal) result.get('averageScore')
      );
    }
    for (ServiceRecommendation rec : recs) {
      rec.Rating = ratingsByService.get(rec.ServiceId);
    }
    return recs;
  }

  public static list<ServiceRecommendation> addHides(
    List<ServiceRecommendation> recs,
    id contactId
  ) {
    // build a map of exclusions for each service ID that the running user has created at the service or contact+service level
    map<id, list<Service_Exclusion__c>> exclusionsByService = new Map<id, list<Service_Exclusion__c>>();
    for (Service_Exclusion__c exclusion : [
      SELECT id, Service__c, Contact__c
      FROM Service_Exclusion__c
      WHERE
        CreatedById = :UserInfo.getUserId()
        AND Service__c IN :IDsFromRecommendations(recs)
        AND (Contact__c = null
        OR Contact__c = :contactId)
      ORDER BY Service__c
    ]) {
      list<Service_Exclusion__c> existing = exclusionsByService.get(
        exclusion.Service__c
      );
      if (existing == null) {
        existing = new List<Service_Exclusion__c>();
      }
      existing.add(exclusion);
      exclusionsByService.put(exclusion.Service__c, existing);
    }
    // iterate the recommendations
    for (ServiceRecommendation rec : recs) {
      // get the exclusions for this service
      list<Service_Exclusion__c> exclusions = exclusionsByService.get(
        rec.ServiceId
      );
      if (exclusions != null && exclusions.size() > 0) {
        rec.Hidden = true;
      }
    }
    return recs;
  }

  public static list<ServiceRecommendation> finalScores(
    List<ServiceRecommendation> recs
  ) {
    // somehow get the weighting for each category, probably cached
    // somehow get the org's min/max distribution for each numerical category, probably cached
    for (ServiceRecommendation rec : recs) {
      rec.Relevance = Integer.valueof((Math.random() * 100));
    }
    return recs;
  }

  public static List<ServiceRecommendation> getComments(
    List<ServiceRecommendation> recs
  ) {
    list<FeedItem> FeedItems = [
      SELECT id, ParentId, Body
      FROM FeedItem
      WHERE ParentId IN :IDsFromRecommendations(recs) AND Type = 'TextPost'
      ORDER BY ParentId
    ];
    map<id, list<string>> feedItemsByService = new Map<id, list<string>>();
    for (feedItem fi : FeedItems) {
      list<string> existing = feedItemsByService.get(fi.ParentId);
      if (existing == null) {
        existing = new List<string>();
      }
      existing.add(fi.Body);
      feedItemsByService.put(fi.ParentId, existing);
    }

    for (ServiceRecommendation rec : recs) {
      list<string> comments = feedItemsByService.get(rec.ServiceId);
      if (comments != null && comments.size() > 0) {
        for (string comment : comments) {
          ServiceRecommendation.Comment commentToAdd = new ServiceRecommendation.Comment();
          commentToAdd.CommentText = comment;
          rec.Comments.add(commentToAdd);
        }
      }
    }
    return recs;
  }

  @AuraEnabled
  public static List<ServiceRecommendation> addNewComment(id serviceId, String newComment){
    FeedItem newFeedItem = new  FeedItem();
    newFeedItem.ParentId = serviceId;
    newFeedItem.Body = newComment;
    newFeedItem.Type = 'TextPost';
  }

  public static List<ServiceRecommendation> addHours(
    List<ServiceRecommendation> recs
  ) {
    map<id, Open_Hours__c> hours = getHoursByService(
      IDsFromRecommendations(recs)
    );
    for (ServiceRecommendation SR : recs) {
      SR.TodaysHours = hours.get(SR.ServiceId);
    }
    return recs;
  }

  public static Client_Profile__c getProfile(id contactId) {
    Client_Profile__c output = [
      SELECT id, Date_Of_Birth__c, Location__Latitude__s, Location__Longitude__s
      FROM Client_Profile__c
      WHERE Contact__c = :contactId
    ];
    if (output.Location__Latitude__s == null) {
      output.Location__Latitude__s = [
        SELECT Default_Latitude__c
        FROM RefRecSettings__mdt
      ]
      .Default_Latitude__c;
    }
    if (output.Location__Longitude__s == null) {
      output.Location__Longitude__s = [
        SELECT Default_Longitude__c
        FROM RefRecSettings__mdt
      ]
      .Default_Longitude__c;
    }
    return output;
  }

  public static decimal calculateAge(Date DOB) {
    return DOB.daysBetween(system.today()) / 365;
  }

  public static list<id> IDsFromRecommendations(
    List<ServiceRecommendation> recs
  ) {
    list<id> output = new List<id>();

    for (ServiceRecommendation rec : recs) {
      output.add(rec.ServiceId);
    }
    return output;
  }

  public static map<id, Open_Hours__c> getHoursByService(list<id> serviceIds) {
    map<id, Open_Hours__c> output = new Map<id, Open_Hours__c>();
    for (Open_Hours__c hours : [
      SELECT Day__c, End_Time__c, Service__c, Start_Time__c
      FROM Open_Hours__c
      WHERE Service__c IN :serviceIds AND Day__c = :whatDayIsIt()
    ]) {
      output.put(hours.Service__c, hours);
    }
    return output;
  }

  public static string whatDayIsIt() {
    list<string> days = new List<string>{
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday'
    };
    Date monday = Date.newInstance(1900, 1, 1);
    return days[Math.mod(monday.daysBetween(system.today()), 7)];
  }
}