force-app/main/default/objects/Client_Profile__c/Client_Profile__c.object-meta.xml
<CustomObject>
    <label>Referral Client Profile</label>
    <pluralLabel>Referral Client Profiles</pluralLabel>
    <description>added from sfdx plugin</description>
    <label>Client Profile</label>
    <pluralLabel>Client Profiles</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>CP-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Profile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Profile</relationshipLabel>
    <relationshipName>Client_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Profile__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <label>Date of Birth</label>
    <type>Date</type>
    <fullName>Date_of_Birth__c</fullName>
</CustomField>

force-app/main/default/objects/Client_Profile__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <label>First Name</label>
    <type>Text</type>
    <fullName>First_Name__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Client_Profile__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <label>Last Name</label>
    <type>Text</type>
    <fullName>Last_Name__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Open_Hours__c/Open_Hours__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Referral Open Hours</label>
    <nameField>
        <displayFormat>Open Hours-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Open Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Hours__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Open_Hours__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Hours</relationshipLabel>
    <relationshipName>Hours</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Service Referral</label>
    <pluralLabel>Service Referrals</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>Ref-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Preferred_Channel__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Channel__c</fullName>
    <label>Preferred Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SMS</fullName>
                <default>true</default>
                <label>SMS</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Score__c.field-meta.xml
<CustomField>
    <label>Score</label>
    <type>Number</type>
    <fullName>Score__c</fullName>
    <scale>0</scale>
    <precision>1</precision>
    <description>1-5 score (star rating)</description>
    <inlineHelpText>1-5 score (star rating)</inlineHelpText>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Maximum_Age__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Age__c</fullName>
    <label>Maximum Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_getRecommendations.cls
@IsTest
public with sharing class Test_getRecommendations {
  static final integer startHour = 9;
  static final integer endHour = 17;

  static testMethod void GoodServiceLooksGood() {
    test.startTest();
    List<ServiceRecommendation> recs = getRecommendations.getRecommendations(
      getTestContact().Id
    );
    test.stopTest();

    system.assertEquals(5, recs[0].Rating);
    system.assertEquals(false, recs[0].Hidden);
    System.assertEquals(startHour, recs[0].TodaysHours.Start_Time__c.hour());
    System.assertEquals(endHour, recs[0].TodaysHours.End_Time__c.hour());
    System.assert(recs[0].Relevance >= 0);
    System.assert(recs[0].Relevance <= 100);
  }

  static testMethod void omitsTeenService() {
    test.startTest();
    List<ServiceRecommendation> recs = getRecommendations.getRecommendations(
      getTestContact().Id
    );
    test.stopTest();
    // you are too old for the teen service
    for (ServiceRecommendation rec : recs) {
      system.assertNotEquals(rec.ProgramName, 'The teen service');
    }
  }

  @testSetup
  static void makeData() {
    //   Create an Account
    Account Provider = new Account();
    Provider.Name = 'GetRecommendations Test Provider';
    insert Provider;

    // create a contact with a profile
    Contact c = new Contact();
    c.FirstName = 'testContact';
    c.LastName = 'Test_getRecommendations';
    c.BirthDate = Date.newInstance(1979, 4, 20);
    insert c;

    Client_Profile__c profile = new Client_Profile__c();
    profile.Contact__c = c.Id;
    profile.Date_of_Birth__c = c.BirthDate;
    profile.First_Name__c = c.Firstname;
    profile.Last_Name__c = c.LastName;
    insert Profile;

    // create 2 services
    List<Service__c> Services = new List<Service__c>();

    Service__c GoodService = new Service__c();
    GoodService.Account__c = Provider.Id;
    GoodService.Name = 'The good service';
    Services.add(GoodService);

    Service__c TeenService = new Service__c();
    TeenService.Account__c = Provider.Id;
    TeenService.Name = 'The teen service';
    TeenService.Maximum_Age__c = 18;
    Services.add(TeenService);

    insert Services;

    // service plus hours
    Open_Hours__c hours = new Open_Hours__c();
    hours.Start_Time__c = Time.newInstance(startHour, 0, 0, 0);
    hours.End_Time__c = Time.newInstance(endHour, 0, 0, 0);
    hours.Service__c = GoodService.Id;
    hours.Day__c = getRecommendations.whatDayIsIt();
    insert hours;

    // service plus exclusions
    // referrals with scores
    Referral__c ref = new Referral__c();
    ref.Contact__c = c.Id;
    ref.Service__c = GoodService.Id;
    ref.Score__c = 5;
    ref.Preferred_Channel__c = 'Email';
    insert ref;
  }

  private static contact getTestContact() {
    return [SELECT id FROM contact WHERE FirstName = 'testContact'];
  }
}