force-app/main/default/objects/Client_Profile__c/Client_Profile__c.object-meta.xml
<CustomObject>
    <label>Referral Client Profile</label>
    <pluralLabel>Referral Client Profiles</pluralLabel>
    <description>added from sfdx plugin</description>
    <label>Client Profile</label>
    <pluralLabel>Client Profiles</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>CP-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Profile__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <label>Date of Birth</label>
    <type>Date</type>
    <fullName>Date_of_Birth__c</fullName>
</CustomField>

force-app/main/default/objects/Client_Profile__c/fields/Home_Owner__c.field-meta.xml
<CustomField>
    <label>Home Owner</label>
    <type>Checkbox</type>
    <fullName>Home_Owner__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Client_Profile__c/fields/Home_Renter__c.field-meta.xml
<CustomField>
    <label>Home Renter</label>
    <type>Checkbox</type>
    <fullName>Home_Renter__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Client_Profile__c/fields/Near_Homeless__c.field-meta.xml
<CustomField>
    <label>Near Homeless</label>
    <type>Checkbox</type>
    <fullName>Near_Homeless__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Client_Profile__c/fields/Runaway__c.field-meta.xml
<CustomField>
    <fullName>Runaway__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Runaway</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RefRecSettings__mdt/RefRecSettings__mdt.object-meta.xml
<CustomObject>
    <label>Referral Recommendations Setting</label>
    <pluralLabel>Referral Recommendations Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/RefRecSettings__mdt/fields/Default_Max_Distance__c.field-meta.xml
<CustomField>
    <fullName>Default_Max_Distance__c</fullName>
    <defaultValue>25</defaultValue>
    <description>In miles, how far from the client or default location should a search extend</description>
    <inlineHelpText>In miles, how far from the client or default location should a search extend</inlineHelpText>
    <label>Default Max Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/All_Types__c.field-meta.xml
<CustomField>
    <fullName>All_Types__c</fullName>
    <label>All Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Goods</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Money</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/City__c.field-meta.xml
<CustomField>
    <label>City</label>
    <type>Text</type>
    <fullName>City__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Employed_full_time__c.field-meta.xml
<CustomField>
    <label>Employed full-time</label>
    <type>Checkbox</type>
    <fullName>Employed_full_time__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Service__c/fields/Employed_part_time__c.field-meta.xml
<CustomField>
    <fullName>Employed_part_time__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Employed part-time</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Home_Owner__c.field-meta.xml
<CustomField>
    <label>Home Owner</label>
    <type>Checkbox</type>
    <fullName>Home_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <description></description>
    <inlineHelpText></inlineHelpText>
</CustomField>

force-app/main/default/objects/Service__c/fields/Homeless__c.field-meta.xml
<CustomField>
    <label>Homeless</label>
    <type>Checkbox</type>
    <fullName>Homeless__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Service__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <scale>4</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Maximum_Age__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Age__c</fullName>
    <label>Maximum Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Minimum_Age__c.field-meta.xml
<CustomField>
    <label>Minimum Age</label>
    <type>Number</type>
    <fullName>Minimum_Age__c</fullName>
    <scale>0</scale>
    <precision>18</precision>
</CustomField>

force-app/main/default/objects/Service__c/fields/Near_Homeless__c.field-meta.xml
<CustomField>
    <fullName>Near_Homeless__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Near Homeless</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Phone__c.field-meta.xml
<CustomField>
    <label>Phone</label>
    <type>Phone</type>
    <fullName>Phone__c</fullName>
</CustomField>

force-app/main/default/objects/Service__c/fields/Preferred__c.field-meta.xml
<CustomField>
    <fullName>Preferred__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Preferred</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Retired__c.field-meta.xml
<CustomField>
    <label>Retired</label>
    <type>Checkbox</type>
    <fullName>Retired__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Service__c/fields/Runaway__c.field-meta.xml
<CustomField>
    <label>Runaway</label>
    <type>Checkbox</type>
    <fullName>Runaway__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service_Tags__c.field-meta.xml
<CustomField>
    <label>Service Tags</label>
    <type>Text</type>
    <fullName>Service_Tags__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Situation_Tags__c.field-meta.xml
<CustomField>
    <label>Situation Tags</label>
    <type>Text</type>
    <fullName>Situation_Tags__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Street__c.field-meta.xml
<CustomField>
    <label>Street</label>
    <type>Text</type>
    <fullName>Street__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Goods</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Money</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Unemployed__c.field-meta.xml
<CustomField>
    <label>Unemployed</label>
    <type>Checkbox</type>
    <fullName>Unemployed__c</fullName>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/Service__c/fields/Website__c.field-meta.xml
<CustomField>
    <label>Website</label>
    <type>Url</type>
    <fullName>Website__c</fullName>
</CustomField>

force-app/main/default/objects/Service__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <label>Zip Code</label>
    <type>Text</type>
    <fullName>Zip_Code__c</fullName>
    <length>10</length>
</CustomField>

force-app/main/default/classes/getRecommendationsServiceQuery.cls
public with sharing class getRecommendationsServiceQuery {

    // list of services with any hard filters
    // hard filters are currently Age
    public static list<Service__c> primaryQuery(Client_Profile__c client, String filterList) {
      if(Schema.Client_Profile__c.SObjectType == Id.valueOf(client.id).getSobjectType()) {
        decimal age = calculateAge(client.Date_Of_Birth__c);
        List<String> filters = new List<String>();
        if(filterList == null || filterList == '')
          filterList = 'Food,Education,Housing,Goods,Money,Transit,Health,Care,Work,Legal';
        
        filters.addALL(filterList.split(','));
        String filterValue = '(\'' + String.join(filters, '\',\'') + '\')';
       
        decimal defaultMaxDistance = [
          SELECT Default_Max_Distance__c
          FROM RefRecSettings__mdt limit 1
        ]
        .Default_Max_Distance__c;
        
        List<Service__c> serList = new List<Service__c>();
        serList = database.query('SELECT id from Service__c where (Minimum_Age__c = null OR Minimum_Age__c < :age) AND (Maximum_Age__c = null OR Maximum_Age__c > :age) AND All_Types__c includes '+ filterValue +' WITH SECURITY_ENFORCED');
            
        return [
          SELECT
            id,
            Name,
            Account__c,
            Account__r.Name,
            Description__c,
            City__c,
            Phone__c,
            Street__c,
            Type__c,
            All_Types__c,
            Website__c,
            Zip_Code__c,
            Preferred__c,
            Near_Homeless__c, 
            Homeless__c,
            Runaway__c,
            Home_Owner__c,
            Home_Renter__c,
            Retired__c,
            Unemployed__c,
            Employed_full_time__c,
            Employed_part_time__c,
            Service_Tags__c,
            Situation_Tags__c,
            DISTANCE(
              Location__c,
              GEOLOCATION(:client.Location__Latitude__s,
                :client.Location__Longitude__s
              ),
              'mi'
            ) dist
          FROM Service__c
          WHERE
            DISTANCE(
              Location__c,
              GEOLOCATION(:client.Location__Latitude__s,
                :client.Location__Longitude__s
              ),
              'mi'
            ) < :defaultMaxDistance
            AND
                Id in : serList
          WITH SECURITY_ENFORCED
        ];
      } else{
        return null;
      }
  }

  public static decimal calculateAge(Date DOB) {
    return DOB.daysBetween(system.today()) / 365;
  }
}