force-app/main/default/objects/Client_Profile__c/Client_Profile__c.object-meta.xml
<CustomObject>
    <label>Referral Client Profile</label>
    <pluralLabel>Referral Client Profiles</pluralLabel>
    <description>added from sfdx plugin</description>
    <label>Client Profile</label>
    <pluralLabel>Client Profiles</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>CP-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Profile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client Profile</relationshipLabel>
    <relationshipName>Client_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Profile__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <label>Date of Birth</label>
    <type>Date</type>
    <fullName>Date_of_Birth__c</fullName>
</CustomField>

force-app/main/default/objects/Open_Hours__c/Open_Hours__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Referral Open Hours</label>
    <nameField>
        <displayFormat>Open Hours-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Open Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Hours__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Open_Hours__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Hours</relationshipLabel>
    <relationshipName>Hours</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Service Referral</label>
    <pluralLabel>Service Referrals</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>Ref-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Score__c.field-meta.xml
<CustomField>
    <label>Score</label>
    <type>Number</type>
    <fullName>Score__c</fullName>
    <scale>0</scale>
    <precision>1</precision>
    <description>1-5 score (star rating)</description>
    <inlineHelpText>1-5 score (star rating)</inlineHelpText>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/City__c.field-meta.xml
<CustomField>
    <label>City</label>
    <type>Text</type>
    <fullName>City__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Maximum_Age__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Age__c</fullName>
    <label>Maximum Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Minimum_Age__c.field-meta.xml
<CustomField>
    <label>Minimum Age</label>
    <type>Number</type>
    <fullName>Minimum_Age__c</fullName>
    <scale>0</scale>
    <precision>18</precision>
</CustomField>

force-app/main/default/objects/Service__c/fields/Phone__c.field-meta.xml
<CustomField>
    <label>Phone</label>
    <type>Phone</type>
    <fullName>Phone__c</fullName>
</CustomField>

force-app/main/default/objects/Service__c/fields/Street__c.field-meta.xml
<CustomField>
    <label>Street</label>
    <type>Text</type>
    <fullName>Street__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Goods</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Money</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Website__c.field-meta.xml
<CustomField>
    <label>Website</label>
    <type>Url</type>
    <fullName>Website__c</fullName>
</CustomField>

force-app/main/default/objects/Service__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <label>Zip Code</label>
    <type>Text</type>
    <fullName>Zip_Code__c</fullName>
    <length>10</length>
</CustomField>

force-app/main/default/classes/getRecommendations.cls
public with sharing class getRecommendations {
  // default version...uses the clientProfileId
  @AuraEnabled
  public static list<ServiceRecommendation> getRecommendations(id contactId) {
    Client_Profile__c CP = getProfile(contactId);
    List<Service__c> services = primaryQuery(CP);

    // convert to ServiceRecommendation
    list<ServiceRecommendation> output = servicesToRecommendations(services);

    // do the hours for each service
    output = addHours(output);
    // do the comments for each service

    // do the Star Rating for each service
    output = addStars(output);
    // final Relevancy score + factors
    output = finalScores(output);

    return output;
  }

  // list of services with any hard filters
  // hard filters are currently Age
  public static list<Service__c> primaryQuery(Client_Profile__c client) {
    decimal age = calculateAge(client.Date_Of_Birth__c);
    return [
      SELECT
        id,
        Name,
        Account__c,
        Account__r.Name,
        Description__c,
        City__c,
        Phone__c,
        Street__c,
        Type__c,
        Website__c,
        Zip_Code__c
      FROM Service__c
      WHERE
        (Minimum_Age__c = null
        OR Minimum_Age__c < :age)
        AND (Maximum_Age__c = null
        OR Maximum_Age__c > :age)
    ];
  }

  public static List<ServiceRecommendation> servicesToRecommendations(
    List<Service__c> services
  ) {
    List<ServiceRecommendation> output = new List<ServiceRecommendation>();
    for (Service__c service : services) {
      ServiceRecommendation SR = new ServiceRecommendation();
      SR.Relevance = 0;
      SR.ServiceId = service.Id;
      SR.ProviderName = service.Account__r.Name;
      SR.AccountId = service.Account__c;
      SR.ProgramName = service.Name;
      SR.ProgramType = service.Type__c;
      SR.ProgramDescription = service.Description__c;
      SR.TodaysHours = null;
      SR.MailingStreet = service.Street__c;
      SR.MailingCity = service.City__c;
      SR.Website = service.Website__c;
      SR.Hidden = false;
      output.add(SR);
    }
    return output;
  }

  public static List<ServiceRecommendation> addStars(
    List<ServiceRecommendation> recs
  ) {
    map<id, decimal> ratingsByService = new Map<id, decimal>();
    for (AggregateResult result : [
      SELECT Service__c, AVG(Score__c) averageScore
      FROM Referral__c
      WHERE Service__c IN :IDsFromRecommendations(recs) AND Score__c != null
      GROUP BY Service__c
    ]) {
      ratingsByService.put(
        (id) result.get('Service__c'),
        (decimal) result.get('averageScore')
      );
    }
    for (ServiceRecommendation rec : recs) {
      rec.Rating = ratingsByService.get(rec.ServiceId);
    }
    return recs;
  }

  public static list<ServiceRecommendation> finalScores(
    List<ServiceRecommendation> recs
  ) {
    for (ServiceRecommendation rec : recs) {
      // TODO: do real scoring!
      rec.Relevance = Integer.valueof((Math.random() * 100));
    }
    return recs;
  }

  public static List<ServiceRecommendation> addHours(
    List<ServiceRecommendation> recs
  ) {
    map<id, Open_Hours__c> hours = gerHoursByService(
      IDsFromRecommendations(recs)
    );
    for (ServiceRecommendation SR : recs) {
      SR.TodaysHours = hours.get(SR.ServiceId);
    }
    return recs;
  }

  public static Client_Profile__c getProfile(id contactId) {
    return [
      SELECT id, Date_Of_Birth__c
      FROM Client_Profile__c
      WHERE Contact__c = :contactId
    ];
  }

  public static decimal calculateAge(Date DOB) {
    return DOB.daysBetween(system.today()) / 365;
  }

  public static list<id> IDsFromRecommendations(
    List<ServiceRecommendation> recs
  ) {
    list<id> output = new List<id>();

    for (ServiceRecommendation rec : recs) {
      output.add(rec.ServiceId);
    }
    return output;
  }

  public static map<id, Open_Hours__c> gerHoursByService(list<id> serviceIds) {
    map<id, Open_Hours__c> output = new Map<id, Open_Hours__c>();
    for (Open_Hours__c hours : [
      SELECT Day__c, End_Time__c, Service__c, Start_Time__c
      FROM Open_Hours__c
      WHERE Service__c IN :serviceIds AND Day__c = :whatDayIsIt()
    ]) {
      output.put(hours.Service__c, hours);
    }
    return output;
  }

  public static string whatDayIsIt() {
    list<string> days = new List<string>{
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday'
    };
    Date monday = Date.newInstance(1900, 1, 1);
    return days[Math.mod(monday.daysBetween(system.today()), 7)];
  }
}