force-app/main/default/objects/Aunt_Bertha_Attribute_Setting__mdt/Aunt_Bertha_Attribute_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Aunt Bertha Attribute Setting</label>
    <pluralLabel>Aunt Bertha Attribute Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Aunt_Bertha_Attribute_Setting__mdt/fields/Attribute_Tag__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Tag__c</fullName>
    <description>This is the query criteria for searching programs available for a zipcode for attributes.</description>
    <inlineHelpText>This is the query criteria for searching programs available for a zipcode for attributes.</inlineHelpText>
    <label>Attribute Tag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aunt_Bertha_Auth_Setting__mdt/Aunt_Bertha_Auth_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This is the auth settings of Aunt Bertha service provider. It stores the username, password and api to make a successful connection to auth bertha service api get a token and make further calls. This is referenced in apex code.</description>
    <label>Aunt Bertha Auth Setting</label>
    <pluralLabel>Aunt Bertha Auth Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Aunt_Bertha_Auth_Setting__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>API Key for Aunt Bertha service provider.</description>
    <inlineHelpText>API Key for Aunt Bertha service provider.</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aunt_Bertha_Auth_Setting__mdt/fields/Hostname__c.field-meta.xml
<CustomField>
    <fullName>Hostname__c</fullName>
    <description>Currently Aunt Bertha have 2 sets of URL, one for authentication and another for getting all programs. This one is for authentication.</description>
    <inlineHelpText>Currently Aunt Bertha have 2 sets of URL, one for authentication and another for getting all programs. This one is for authentication.</inlineHelpText>
    <label>Hostname</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aunt_Bertha_Auth_Setting__mdt/fields/Hostname_Program__c.field-meta.xml
<CustomField>
    <fullName>Hostname_Program__c</fullName>
    <description>Currently Aunt Bertha have 2 sets of URL, one for authentication and another for getting all programs. This one is for getting all Programs.</description>
    <inlineHelpText>Currently Aunt Bertha have 2 sets of URL, one for authentication and another for getting all programs. This one is for getting all Programs.</inlineHelpText>
    <label>Hostname Program</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aunt_Bertha_Auth_Setting__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password for Aunt Bertha service provider.</description>
    <inlineHelpText>Password for Aunt Bertha service provider.</inlineHelpText>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aunt_Bertha_Auth_Setting__mdt/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username for Aunt Bertha service provider.</description>
    <inlineHelpText>Username for Aunt Bertha service provider.</inlineHelpText>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Provider_ZipCode_Search__mdt/Service_Provider_ZipCode_Search__mdt.object-meta.xml
<CustomObject>
    <description>This data object will be store zip codes which will be utilized for searching programs near the zip codes.</description>
    <label>Service Provider ZipCode Search</label>
    <pluralLabel>Service Provider ZipCodes Search</pluralLabel>
</CustomObject>

force-app/main/default/objects/Service_Provider_ZipCode_Search__mdt/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <label>Zipcode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuntBerthaServiceBatchClass.cls
global class AuntBerthaServiceBatchClass implements 
        Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    Set<String> querySet = new Set<String>();
    Map<String, String> authSet = new Map<String, String>();
    public AuntBerthaServiceBatchClass() {
        //get auth details in the constructor
        Aunt_Bertha_Auth_Setting__mdt abSetting = [SELECT MasterLabel, DeveloperName, 
                                                        API_Key__c ,Username__c, Password__c, Hostname__c, Hostname_Program__c
                                                    FROM Aunt_Bertha_Auth_Setting__mdt LIMIT 1];


        authSet.put('API_Key__c', abSetting.API_Key__c);
        authSet.put('Username__c', abSetting.Username__c);
        authSet.put('Password__c', abSetting.Password__c);
        authSet.put('Hostname__c', abSetting.Hostname__c + '/authenticate');
        authSet.put('Hostname_Program__c', abSetting.Hostname_Program__c);
        authSet.put('MethodType', 'POST');


    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return Database.getQueryLocator('SELECT Zipcode__c from Service_Provider_ZipCode_Search__mdt');
    }
    global void execute(Database.BatchableContext bc, List<Service_Provider_ZipCode_Search__mdt> records){
        
        //get all attribute tags
        Aunt_Bertha_Attribute_Setting__mdt[] attributeTags = [SELECT Attribute_Tag__c from Aunt_Bertha_Attribute_Setting__mdt];



        // process each batch of records
        List<Service_Provider_ZipCode_Search__mdt> serviceZipCodes = records;
        for(Service_Provider_ZipCode_Search__mdt serviceZipCode : serviceZipCodes) {
            System.debug(LoggingLevel.DEBUG, '---> zip code ' + serviceZipCode.Zipcode__c);
            for (Aunt_Bertha_Attribute_Setting__mdt attributeTag : attributeTags) {
                System.debug(LoggingLevel.DEBUG, '---> attribute tag ' + attributeTag.Attribute_Tag__c);
                String query = '/zipcodes/'+ serviceZipCode.Zipcode__c + '/programs?attributeTag=' + attributeTag.Attribute_Tag__c; 
                querySet.add(query);
            }

        }


      
    }    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
        System.debug(LoggingLevel.DEBUG, '---> Start of finish');
        //get auth details
        System.debug(LoggingLevel.DEBUG, '---> auth details ' + authSet.size());
        List<String> queryParams = new List<String>();
        //get query details
        System.debug(LoggingLevel.DEBUG, '---> total # of query produced ' + querySet.size());
        for(String s : querySet) {
            System.debug(LoggingLevel.DEBUG, '---> query url ' + s);
            queryParams.add(s);

        }
        ServiceProviderClient.processAuthBerthaServiceFromBatch(authSet, queryParams);
        
        AsyncApexJob batchJobDetails = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        System.debug(LoggingLevel.DEBUG, '---> job details ' + batchJobDetails);                    
        System.debug(LoggingLevel.DEBUG, '---> End of finish');
    }     
}