force-app/main/default/objects/Contact/fields/Mobile_Phone_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Phone_Carrier__c</fullName>
    <description>The phone carrier for the contact&apos;s mobile phone.</description>
    <inlineHelpText>The phone carrier for the contact&apos;s mobile phone.</inlineHelpText>
    <label>Mobile Phone Carrier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AT&amp;T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Open_Hours__c/Open_Hours__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Referral Open Hours</label>
    <nameField>
        <displayFormat>Open Hours-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referral Open Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Open_Hours__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Open_Hours__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Hours</relationshipLabel>
    <relationshipName>Hours</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/Referral__c.object-meta.xml
<CustomObject>
    <label>Service Referral</label>
    <pluralLabel>Service Referrals</pluralLabel>
    <description>added from sfdx plugin</description>
    <nameField>
        <type>AutoNumber</type>
        <label>Name</label>
        <displayFormat>Ref-{0}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Preferred_Channel__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Channel__c</fullName>
    <label>Preferred Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SMS</fullName>
                <default>true</default>
                <label>SMS</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Score__c.field-meta.xml
<CustomField>
    <label>Score</label>
    <type>Number</type>
    <fullName>Score__c</fullName>
    <scale>0</scale>
    <precision>1</precision>
    <description>1-5 score (star rating)</description>
    <inlineHelpText>1-5 score (star rating)</inlineHelpText>
</CustomField>

force-app/main/default/objects/Referral__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Referrals</relationshipLabel>
    <relationshipName>Referrals</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/City__c.field-meta.xml
<CustomField>
    <label>City</label>
    <type>Text</type>
    <fullName>City__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Maximum_Age__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Age__c</fullName>
    <label>Maximum Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Minimum_Age__c.field-meta.xml
<CustomField>
    <label>Minimum Age</label>
    <type>Number</type>
    <fullName>Minimum_Age__c</fullName>
    <scale>0</scale>
    <precision>18</precision>
</CustomField>

force-app/main/default/objects/Service__c/fields/Phone__c.field-meta.xml
<CustomField>
    <label>Phone</label>
    <type>Phone</type>
    <fullName>Phone__c</fullName>
</CustomField>

force-app/main/default/objects/Service__c/fields/Street__c.field-meta.xml
<CustomField>
    <label>Street</label>
    <type>Text</type>
    <fullName>Street__c</fullName>
    <length>255</length>
</CustomField>

force-app/main/default/objects/Service__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Goods</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Money</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/fields/Website__c.field-meta.xml
<CustomField>
    <label>Website</label>
    <type>Url</type>
    <fullName>Website__c</fullName>
</CustomField>

force-app/main/default/objects/Service__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <label>Zip Code</label>
    <type>Text</type>
    <fullName>Zip_Code__c</fullName>
    <length>10</length>
</CustomField>

force-app/main/default/classes/Test_ReferralEmailTemplateController.cls
@IsTest
public  class Test_ReferralEmailTemplateController {

    @TestSetup
    static void makeData(){
        Contact cont = new Contact (
            FirstName = 'Test',
            LastName = 'Tester',
            Email = 'testy@tester.org',
            Phone = '8885551212',
            MobilePhone = '8005551212',
            Mobile_Phone_Carrier__c = 'AT&T'
        );
        insert cont;

        Service__c svc = new Service__c (
            Name = 'Test Service',
            City__c = 'Boston',
            Description__c = 'Test Service for Testing',
            Maximum_Age__c = 100,
            Minimum_Age__c = 12,
            Phone__c = '4155551212',
            Street__c = '123 Main Street',
            Type__c = 'Care',
            Website__c = 'testing@testservice.org',
            Zip_Code__c = '12345'
        );
        insert svc;

        Open_Hours__c open = new Open_Hours__c (
            Day__c = 'Monday',
            Start_Time__c = Time.newInstance(9, 0, 0, 0),
            End_Time__c = Time.newInstance(17, 0, 0, 0),
            Service__c = svc.Id
        );
        insert open;

        Referral__c ref = new Referral__c (
            Contact__c = cont.Id,
            Preferred_Channel__c = 'SMS',
            Score__c = 5,
            Service__c = svc.Id
        );
        insert ref;
        
    }

    static testMethod void testGetData() {
        List<Contact> contacts = [
            SELECT 
                Id
            FROM Contact
            WHERE LastName = 'Tester'
        ];

        List<Referral__c> referrals = [
            SELECT
                Id
            FROM Referral__c
            WHERE Contact__c = :contacts[0].Id
        ];

        Test.startTest();
        ReferralEmailTemplateController controller = new ReferralEmailTemplateController();
        controller.referralId = referrals[0].Id;
        Test.stopTest();

        Referral__c referral = controller.referral;
        System.assertEquals('Care',referral.Service__r.Type__c);
        System.assertEquals('Test Service',referral.Service__r.Name);
        System.assertEquals('Tester',referral.Contact__r.LastName);

        System.assertEquals('Monday: 9:00 AM - 5:00 PM', controller.openHoursString);
    }


}