force-app/main/default/objects/Carrier_Setting__mdt/Carrier_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Holds carrier settings for Email to SMS function</description>
    <label>Carrier Setting</label>
    <pluralLabel>Carrier Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Carrier_Setting__mdt/fields/Carrier_Name__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Name__c</fullName>
    <description>The name of the carrier. This should match one of the values in the Contact&apos;s picklist.</description>
    <inlineHelpText>The name of the carrier. This should match one of the values in the Contact&apos;s picklist.</inlineHelpText>
    <label>Carrier Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier_Setting__mdt/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <description>The domain portion - following the @ - of the carrier email</description>
    <inlineHelpText>The domain portion - following the @ - of the carrier email</inlineHelpText>
    <label>Email Domain</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/carrierSettingsData.cls
public with sharing class carrierSettingsData {
    
    public static String getEmailForCarrier (String carrierName) {
        if (!Schema.sObjectType.Carrier_Setting__mdt.isAccessible()){
            throw new CarrierServicenException(
                System.Label.flsError);
               
             } else {  
        List<Carrier_Setting__mdt> settings = [
            SELECT 
                Email_Domain__c
            FROM Carrier_Setting__mdt
            WHERE Carrier_Name__c = :carrierName
        ];

        if (settings.size() > 0) {
            return settings[0].Email_Domain__c;
        } else {
            return null;
            }
        }
    }
    public class CarrierServicenException extends Exception {
    }
}